setwd("/Users/ethanwang/downloads/DSCI_310/dsci_310_ia4_EthanWang")
file.exists("source/generate_figures.R")
source("../source/generate_figures.R")
install.packages("docopt")
install.packages("gridExtra")
source("../source/generate_figures.R")
main("data/00030067-eng.csv", "results")
file.exists("../results/horses_sd.csv")
horses_sd_table <- read_csv("../results/horses_sd.csv")
print(horses_sd_table)
tinytex::uninstall_tinytex()
tinytex::install_tinytex()
tinytex::tlmgr_version()
